### ISSUE TITLE
Can't render PNG

### ISSUE THREAD

**Issue by Marahin** [beevelop/docker-shields#2]
Hello,

Shields.io allow for .png rendering instead of .svg. However this does not work on this docker container.

*I assume* that's because there's no `imagemagick` added. [See my fix for details](https://github.com/Marahin/docker-shields/commit/93f5a067521fd110de039c8ad27957698933eda6)

Please advise.

**Comment by beevelop** [comment]
Do you have an example URL to test the behaviour? What happens when you request a PNG image (error logs,...)?
Did you already have the chance to check if your fork solves the problem?

**Comment by Marahin** [comment]
@beevelop I'm sorry, I had to miss the notification for your comment. 
Nothing happens. I also forgot to add a pull request; adding `imagemagick` to `apt install` solved the issue. 

Good job! And thanks for fixing it.

**Comment by beevelop** [comment]
No problem, thanks you for reporting the bug!
