### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by MartinGonzalez** [beevelop/docker-shields#4]
I have downloaded the project and run it but it's not working (i tried with the docker compose and docker run)

**Comment by beevelop** [comment]
Define „not working“. Do you get any exceptions?

**Comment by MartinGonzalez** [comment]
@beevelop  Thanks for the fast response and sorry for the poor description.
 I ve downloaded the repo and followed the instructions.
Run
``` 
docker-compose up -d
```

and i have the two containers running (shields and Varnish) and i tried entering 
http://shields.example.com
and
localhost:3000 (because shields.io server use this one)

also i tried 
```
docker run -d --name shields -p 80:80 \
    -e INFOSITE="http://shields.example.com" \
    beevelop/shields
```

even changing the port binding but i have no connection to it, i mean i cannot see shield.io page like i saw when building the server from their repo using npm
